import './index.pug';
import './index.scss';
import './buttons/buttons.pug';
import './buttons/buttons.scss';
import './buttons/buttons.js';
import './arrows/arrow.pug';
import './arrows/arrow.scss';
import './arrows/arrow.js';
import './pie-chart/percentages-chart/percentages.pug';
import './pie-chart/percentages-chart/percentages.scss';
import './pie-chart/percentages-chart/percentages.js';
import './pie-chart/donut-chart/donut.pug';
import './pie-chart/donut-chart/donut.scss';
import './pie-chart/donut-chart/donut.js';
import $ from 'jquery';